### ISSUE TITLE
make with error atlassian

### ISSUE THREAD

**Issue by kubex75** [zarplata/zabbix-agent-extension-sentry#1]
Hello 

After i run make i've got:

```
github.com/atlassian/go-sentry-api
github.com/docopt/docopt-go
# github.com/atlassian/go-sentry-api
vendor/src/github.com/atlassian/go-sentry-api/client.go:60: unknown http.Client field 'Timeout' in struct literal
vendor/src/github.com/atlassian/go-sentry-api/team.go:29: undefined: http.MethodPost
vendor/src/github.com/atlassian/go-sentry-api/team.go:40: undefined: http.MethodDelete
github.com/reconquest/hierr-go
make: *** [build] Error 2
```
what should i do?
Thanks

**Comment by akitsul** [comment]
Hello, 
1. show all stdout after run make
2. show `echo $GOPATH`
3. show `go version`
4. show `git submodule status` in project dir.

**Comment by kubex75** [comment]
make works with the latest version of golang (i have some old version and didn't check that)
Thank you very much for answer and help and of course for that great plugin ;)
